# Generated by Django 6.0.2 on 2026-02-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_tasks', to='core.organization')),
            ],
            options={
                'verbose_name': 'Coding Task',
                'verbose_name_plural': 'Coding Tasks',
                'db_table': 'coding_tasks',
                'ordering': ['order_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.codingtask')),
            ],
            options={
                'verbose_name': 'Coding Test Case',
                'verbose_name_plural': 'Coding Test Cases',
                'db_table': 'coding_test_cases',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_topics', to='core.organization')),
            ],
            options={
                'verbose_name': 'Coding Topic',
                'verbose_name_plural': 'Coding Topics',
                'db_table': 'coding_topics',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='codingtask',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='coding.codingtopic'),
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('passed_count', models.IntegerField(blank=True, null=True)),
                ('failed_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_no', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_submissions', to='core.organization')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingtask')),
            ],
            options={
                'verbose_name': 'Coding Submission',
                'verbose_name_plural': 'Coding Submissions',
                'db_table': 'coding_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='coding_subm_student_f70301_idx'), models.Index(fields=['task'], name='coding_subm_task_id_c463a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_progress', to='students.studentprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='coding.codingtask')),
            ],
            options={
                'verbose_name': 'Coding Progress',
                'verbose_name_plural': 'Coding Progress',
                'db_table': 'coding_progress',
                'ordering': ['-updated_at'],
                'unique_together': {('student_profile', 'exercise')},
            },
        ),
    ]
