# Generated by Django 6.0.2 on 2026-02-11 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingsubmission',
            name='score',
            field=models.IntegerField(blank=True, help_text='Optional score for this submission', null=True),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['student', 'task'], name='coding_subm_student_f900f3_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['created_at'], name='coding_subm_created_493471_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['topic'], name='coding_task_topic_i_e42f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['is_active'], name='coding_task_is_acti_60efe7_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['order_index'], name='coding_task_order_i_d7f221_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtestcase',
            index=models.Index(fields=['task'], name='coding_test_task_id_072a11_idx'),
        ),
    ]
