# Generated by Django 6.0.2 on 2026-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_submission_details_json'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codingsubmission',
            name='coding_subm_task_stu_idx',
        ),
        migrations.RemoveIndex(
            model_name='codingtestcase',
            name='coding_test_task_order_idx',
        ),
        migrations.AlterField(
            model_name='codingsubmission',
            name='details_json',
            field=models.JSONField(blank=True, default=list, help_text='Per-test results [{test_case_id, passed, output?, expected?}]. Teacher-only for hidden.'),
        ),
    ]
