# Generated by Django 6.0.2 on 2026-02-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0005_remove_codingsubmission_coding_subm_task_stu_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtopic',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
