# Generated by Django 6.0.2 on 2026-02-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0006_archive_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtask',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
