# Generated by Django for PROMPT 5/8 - Coding system enhancements

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0007_add_is_archived_codingtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtopic',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_coding_topics',
                to=settings.AUTH_USER_MODEL,
                db_column='created_by_id',
            ),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='run_type',
            field=models.CharField(
                choices=[('RUN', 'Run'), ('SUBMIT', 'Submit')],
                db_index=True,
                default='SUBMIT',
                max_length=10,
            ),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
