# Generated by Django 6.0.2 on 2026-02-15 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0008_coding_submission_run_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtopic',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
