# Generated by Django 6.0.2 on 2026-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0010_submission_task_student_created_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codingsubmission',
            name='coding_subm_task_stu_created_idx',
        ),
    ]
