# Generated by Django 6.0.2 on 2026-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, help_text="Force password change on next login"
            ),
        ),
    ]
