# Generated by Django 6.0.2 on 2026-02-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_organization_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_org_idx',
        ),
    ]
