# Generated by Django 6.0.2 on 2026-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_payments_org_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sequence_number',
            field=models.IntegerField(blank=True, db_index=True, help_text='Sequential payment number (globally ordered by date)', null=True),
        ),
    ]
