# Generated by Django 6.0.2 on 2026-02-07 18:52

from django.db import migrations, models


def backfill_is_deleted(apps, schema_editor):
    StudentProfile = apps.get_model("students", "StudentProfile")
    StudentProfile.objects.filter(deleted_at__isnull=False).update(is_deleted=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_is_deleted, noop),
    ]
