# Generated by Django 6.0.2 on 2026-02-07 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_add_is_deleted_to_student_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportedCredentialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("CSV_IMPORT", "CSV Import")],
                        default="CSV_IMPORT",
                        max_length=50,
                    ),
                ),
                ("student_full_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                (
                    "parent_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("grade", models.CharField(blank=True, max_length=50, null=True)),
                ("initial_password_encrypted", models.TextField(blank=True, null=True)),
                ("password_is_one_time", models.BooleanField(default=True)),
                ("password_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by_id",
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_credential_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "parent"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_credential_as_parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imported_credential_records_as_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imported Credential Record",
                "verbose_name_plural": "Imported Credential Records",
                "db_table": "imported_credential_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_by"], name="imported_cr_created_9e7cf2_idx"
                    ),
                    models.Index(
                        fields=["student"], name="imported_cr_student_6aeced_idx"
                    ),
                ],
            },
        ),
    ]
