# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_add_balance_ledger"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="balanceledger",
            new_name="balance_led_student_4cef6f_idx",
            old_name="balance_led_student_date_idx",
        ),
        migrations.RenameIndex(
            model_name="balanceledger",
            new_name="balance_led_group_i_b530d7_idx",
            old_name="balance_led_group_date_idx",
        ),
        migrations.RenameIndex(
            model_name="balancetransaction",
            new_name="balance_tra_student_c896d9_idx",
            old_name="balance_tra_student_9b0b0d_idx",
        ),
        migrations.RenameIndex(
            model_name="balancetransaction",
            new_name="balance_tra_group_i_5e4336_idx",
            old_name="balance_tra_group_i_8a1c2e_idx",
        ),
    ]
