# Generated by Django 6.0.2 on 2026-02-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_importedcredentialrecord_search_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='importedcredentialrecord',
            name='imported_cr_fullna_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedcredentialrecord',
            name='imported_cr_stuemail_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedcredentialrecord',
            name='imported_cr_paremail_idx',
        ),
    ]
