"""
Teacher API URLs
"""
from django.urls import path
from ..views.teacher import (
    teacher_stats_view,
    teacher_students_view,
    teacher_student_restore_view,
    teacher_groups_view,
    teacher_group_students_view,
    teacher_move_student_view,
    teacher_payments_view,
)
from ..views.archive import (
    archive_payments_view,
    archive_groups_view,
    archive_students_view,
    restore_payment_view,
    restore_group_view,
)
from attendance.views.teacher import (
    teacher_attendance_grid_view,
    teacher_attendance_update_view,
    attendance_group_daily_view,
    attendance_save_view,
    attendance_group_monthly_view,
    attendance_student_daily_view,
)
from coding.views.archive import (
    archive_coding_topics_view,
    archive_coding_tasks_view,
    restore_coding_topic_view,
    restore_coding_task_view,
    hard_delete_coding_topic_view,
    hard_delete_coding_task_view,
)
from coding.views.teacher import (
    teacher_coding_list_view,
    teacher_coding_detail_view,
    teacher_coding_monitor_view,
    teacher_coding_testcases_list_view,
    teacher_coding_testcase_detail_view,
    teacher_coding_topics_view,
    teacher_coding_topic_delete_view,
    teacher_coding_submissions_list_view,
    teacher_coding_submission_detail_view,
    teacher_student_submissions_view,
)
from tests.views.teacher import teacher_tests_list_view, teacher_test_result_create_view
from tests.views.archive import (
    archive_question_topics_view,
    archive_questions_view,
    archive_exams_view,
    archive_pdfs_view,
    restore_question_topic_view,
    restore_question_view,
    restore_exam_view,
    restore_pdf_view,
    hard_delete_question_topic_view,
    hard_delete_question_view,
    hard_delete_exam_view,
    hard_delete_pdf_view,
)
from tests.views.exams import (
    teacher_question_topics_view,
    teacher_question_topic_delete_view,
    teacher_questions_view,
    teacher_question_detail_view,
    teacher_exams_view,
    teacher_exam_detail_view,
    teacher_exam_add_question_view,
    teacher_exam_remove_question_view,
    teacher_exam_assign_groups_view,
    teacher_exam_start_now_view,
    teacher_exam_stop_view,
    teacher_exam_create_run_view,
    teacher_exam_runs_list_view,
    teacher_run_attempts_view,
    teacher_run_reset_student_view,
    teacher_exam_attempts_view,
    teacher_exam_attempts_cleanup_view,
    teacher_exam_reset_student_view,
    teacher_attempt_detail_view,
    teacher_attempt_grade_view,
    teacher_attempt_publish_view,
    teacher_attempt_restart_view,
    teacher_attempt_reopen_view,
    teacher_pdfs_view,
    teacher_pdf_detail_view,
)
from students.views.bulk_import import (
    bulk_import_students_view,
    bulk_import_preview_view,
    bulk_import_confirm_view,
)
from students.views.credentials import (
    credentials_list_view,
    credentials_reveal_view,
    credentials_export_view,
)

app_name = 'teacher'

urlpatterns = [
    path('stats', teacher_stats_view, name='stats'),
    path('students', teacher_students_view, name='students-list'),
    path('students/<int:pk>', teacher_students_view, name='students-detail'),
    path('students/<int:pk>/restore', teacher_student_restore_view, name='students-restore'),
    path('students/<int:pk>/hard', teacher_students_view, name='students-hard-delete'),
    path('groups', teacher_groups_view, name='groups-list'),
    path('groups/<int:pk>/restore', restore_group_view, name='restore-group'),
    path('groups/<int:pk>', teacher_groups_view, name='groups-detail'),
    path('groups/<int:group_id>/students', teacher_group_students_view, name='group-students-add'),
    path('groups/<int:group_id>/students/<int:student_id>', teacher_group_students_view, name='group-students-remove'),
    path('groups/move-student', teacher_move_student_view, name='move-student'),
    path('payments', teacher_payments_view, name='payments-list'),
    path('payments/<int:pk>/restore', restore_payment_view, name='restore-payment'),
    path('payments/<int:pk>', teacher_payments_view, name='payments-detail'),
    path('attendance', teacher_attendance_grid_view, name='attendance-grid'),
    path('attendance/update', teacher_attendance_update_view, name='attendance-update'),
    path('attendance/group/<int:group_id>/daily', attendance_group_daily_view, name='attendance-daily'),
    path('attendance/save', attendance_save_view, name='attendance-save'),
    path('attendance/group/<int:group_id>/monthly', attendance_group_monthly_view, name='attendance-monthly'),
    path('attendance/group/<int:group_id>/student/<int:student_id>/daily', attendance_student_daily_view, name='attendance-student-daily'),
    path('archive/coding-topics', archive_coding_topics_view, name='archive-coding-topics'),
    path('archive/coding-tasks', archive_coding_tasks_view, name='archive-coding-tasks'),
    path('coding/topics', teacher_coding_topics_view, name='coding-topics'),
    path('coding/topics/<int:pk>', teacher_coding_topic_delete_view, name='coding-topic-delete'),
    path('coding/topics/<int:pk>/restore', restore_coding_topic_view, name='coding-topic-restore'),
    path('coding/topics/<int:pk>/hard-delete', hard_delete_coding_topic_view, name='coding-topic-hard-delete'),
    path('coding', teacher_coding_list_view, name='coding-list'),
    path('coding/<int:pk>', teacher_coding_detail_view, name='coding-detail'),
    path('coding/<int:pk>/restore', restore_coding_task_view, name='coding-task-restore'),
    path('coding/<int:pk>/hard-delete', hard_delete_coding_task_view, name='coding-task-hard-delete'),
    path('coding/<int:pk>/testcases', teacher_coding_testcases_list_view, name='coding-testcases'),
    path('coding/testcases/<int:caseId>', teacher_coding_testcase_detail_view, name='coding-testcase-detail'),
    path('coding-monitor', teacher_coding_monitor_view, name='coding-monitor'),
    path('coding/submissions', teacher_coding_submissions_list_view, name='coding-submissions'),
    path('coding/submissions/<int:pk>', teacher_coding_submission_detail_view, name='coding-submission-detail'),
    path('coding/student/<int:student_id>/submissions', teacher_student_submissions_view, name='student-submissions'),
    path('tests', teacher_tests_list_view, name='tests-list'),
    path('test-results', teacher_test_result_create_view, name='test-results-create'),
    path('archive/question-topics', archive_question_topics_view, name='archive-question-topics'),
    path('archive/questions', archive_questions_view, name='archive-questions'),
    path('archive/exams', archive_exams_view, name='archive-exams'),
    path('archive/pdfs', archive_pdfs_view, name='archive-pdfs'),
    path('archive/payments', archive_payments_view, name='archive-payments'),
    path('archive/groups', archive_groups_view, name='archive-groups'),
    path('archive/students', archive_students_view, name='archive-students'),
    path('question-topics', teacher_question_topics_view, name='question-topics'),
    path('question-topics/<int:pk>', teacher_question_topic_delete_view, name='question-topic-delete'),
    path('question-topics/<int:pk>/restore', restore_question_topic_view, name='question-topic-restore'),
    path('question-topics/<int:pk>/hard-delete', hard_delete_question_topic_view, name='question-topic-hard-delete'),
    path('questions', teacher_questions_view, name='questions'),
    path('questions/<int:pk>', teacher_question_detail_view, name='question-detail'),
    path('questions/<int:pk>/restore', restore_question_view, name='question-restore'),
    path('questions/<int:pk>/hard-delete', hard_delete_question_view, name='question-hard-delete'),
    path('exams', teacher_exams_view, name='exams'),
    path('exams/<int:pk>', teacher_exam_detail_view, name='exam-detail'),
    path('exams/<int:pk>/restore', restore_exam_view, name='exam-restore'),
    path('exams/<int:pk>/hard-delete', hard_delete_exam_view, name='exam-hard-delete'),
    path('exams/<int:exam_id>/questions', teacher_exam_add_question_view, name='exam-add-question'),
    path('exams/<int:exam_id>/questions/<int:question_id>', teacher_exam_remove_question_view, name='exam-remove-question'),
    path('exams/<int:exam_id>/assign', teacher_exam_assign_groups_view, name='exam-assign-groups'),
    path('exams/<int:exam_id>/start-now', teacher_exam_start_now_view, name='exam-start-now'),
    path('exams/<int:exam_id>/stop', teacher_exam_stop_view, name='exam-stop'),
    path('exams/<int:exam_id>/create-run', teacher_exam_create_run_view, name='exam-create-run'),
    path('exams/<int:exam_id>/runs', teacher_exam_runs_list_view, name='exam-runs'),
    path('runs/<int:run_id>/attempts', teacher_run_attempts_view, name='run-attempts'),
    path('runs/<int:run_id>/reset-student', teacher_run_reset_student_view, name='run-reset-student'),
    path('exams/<int:exam_id>/attempts', teacher_exam_attempts_view, name='exam-attempts'),
    path('exams/<int:exam_id>/attempts/cleanup', teacher_exam_attempts_cleanup_view, name='exam-attempts-cleanup'),
    path('exams/<int:exam_id>/reset-student', teacher_exam_reset_student_view, name='exam-reset-student'),
    path('attempts/<int:attempt_id>', teacher_attempt_detail_view, name='attempt-detail'),
    path('attempts/<int:attempt_id>/grade', teacher_attempt_grade_view, name='attempt-grade'),
    path('attempts/<int:attempt_id>/publish', teacher_attempt_publish_view, name='attempt-publish'),
    path('attempts/<int:attempt_id>/restart', teacher_attempt_restart_view, name='attempt-restart'),
    path('attempts/<int:attempt_id>/reopen', teacher_attempt_reopen_view, name='attempt-reopen'),
    path('pdfs', teacher_pdfs_view, name='pdfs'),
    path('pdfs/<int:pk>', teacher_pdf_detail_view, name='pdf-detail'),
    path('pdfs/<int:pk>/restore', restore_pdf_view, name='pdf-restore'),
    path('pdfs/<int:pk>/hard-delete', hard_delete_pdf_view, name='pdf-hard-delete'),
    path('bulk-import', bulk_import_students_view, name='bulk-import'),
    path('bulk-import/preview', bulk_import_preview_view, name='bulk-import-preview'),
    path('bulk-import/confirm', bulk_import_confirm_view, name='bulk-import-confirm'),
    path('credentials', credentials_list_view, name='credentials-list'),
    path('credentials/export.csv', credentials_export_view, name='credentials-export'),
    path('credentials/<int:pk>/reveal', credentials_reveal_view, name='credentials-reveal'),
]
