# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_type_e163c0_idx",
            old_name="notificatio_type_is_r_7a8b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_student_61138d_idx",
            old_name="notificatio_student_is_r_idx",
        ),
    ]
