# Generated by Django 6.0.2 on 2026-02-19 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_monthly_fee'),
        ('notifications', '0002_rename_notificatio_type_is_r_7a8b2c_idx_notificatio_type_e163c0_idx_and_more'),
        ('students', '0006_rename_balance_led_student_date_idx_balance_led_student_4cef6f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('student', 'type'), name='unique_active_notification_per_student_type'),
        ),
    ]
