# Generated by Django 6.0.2 on 2026-02-07 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidate_duplicates(apps, schema_editor):
    """Keep one record per (student_profile, lesson_date). Prefer 'present'."""
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    from django.db.models import Count

    duplicates = (
        AttendanceRecord.objects.values("student_profile", "lesson_date")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for dup in duplicates:
        records = AttendanceRecord.objects.filter(
            student_profile_id=dup["student_profile"],
            lesson_date=dup["lesson_date"],
        ).order_by("id")
        # Keep first with 'present', else keep first
        keeper = None
        for r in records:
            if r.status == "present":
                keeper = r
                break
        keeper = keeper or records.first()
        for r in records:
            if r.id != keeper.id:
                r.delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("core", "0001_initial"),
        ("groups", "0001_initial"),
        ("students", "0002_add_is_deleted_to_student_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicates, noop),
        migrations.RemoveIndex(
            model_name="attendancerecord",
            name="attendance__group_i_0c2e6b_idx",
        ),
        migrations.AlterUniqueTogether(
            name="attendancerecord",
            unique_together={("student_profile", "lesson_date")},
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                    ("excused", "Excused"),
                ],
                default="present",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["lesson_date"], name="attendance__lesson__b1fc87_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="attendancerecord",
            name="note",
        ),
    ]
