# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_add_lesson_held"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="grouplessonsession",
            new_name="group_lesso_group_i_66b92c_idx",
            old_name="group_lesso_group_i_2d4f1a_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonheld",
            new_name="lessons_hel_group_i_27c401_idx",
            old_name="lessons_hel_group_id_date_idx",
        ),
        migrations.RenameIndex(
            model_name="lessonheld",
            new_name="lessons_hel_date_9a74c2_idx",
            old_name="lessons_hel_date_idx",
        ),
    ]
