# Generated by Django 6.0.2 on 2026-02-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_group_lesso_group_i_2d4f1a_idx_group_lesso_group_i_66b92c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonheld',
            name='is_finalized',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether lesson is finalized (locked for editing)'),
        ),
    ]
