# Generated by Django 6.0.2 on 2026-02-15 15:41
# Migration: add display_name_is_manual; default empty lesson_days to [2, 4] (Tue/Thu) per legacy 2-lessons/week.

from django.db import migrations, models


def default_empty_lesson_days(apps, schema_editor):
    """Set lesson_days=[2,4] (Tue/Thu) for existing groups with empty days_of_week."""
    Group = apps.get_model("groups", "Group")
    for g in Group.objects.all():
        dow = g.days_of_week
        if dow is None or (isinstance(dow, list) and len(dow) == 0):
            g.days_of_week = [2, 4]
            g.save(update_fields=["days_of_week"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="display_name_is_manual",
            field=models.BooleanField(
                default=False, help_text="If True, do not auto-overwrite display_name"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="days_of_week",
            field=models.JSONField(
                blank=True, default=list, help_text="e.g. [1,2,3,4]; Mon=1..Sun=7"
            ),
        ),
        migrations.RunPython(default_empty_lesson_days, noop),
    ]
