# Generated by Django 6.0.2
# Migration: Parse days from display_name for backward compatibility.
# "1-4 11:00" => [1,4], "1-3-5 10:00" => [1,3,5]. NOT range: "1-4" = days 1 and 4 only.

import re
from django.db import migrations


def parse_days_from_display_name(display_name):
    """Parse days from display_name. '1-4 11:00' => [1,4]. Returns None if fails."""
    if not display_name or not isinstance(display_name, str):
        return None
    s = display_name.strip()
    m = re.match(r"^([\d\-,\s]+?)(?:\s+\d{1,2}[:\.]\d{2})?", s)
    day_str = (m.group(1) if m else s).strip() if s else ""
    if not day_str:
        return None
    days = []
    for part in re.split(r"[,\-\s]+", day_str):
        try:
            n = int(part)
            if 1 <= n <= 7 and n not in days:
                days.append(n)
        except (ValueError, TypeError):
            pass
    return sorted(days) if days else None


def backfill_days_from_display_name(apps, schema_editor):
    """Parse display_name to fix days_of_week. '1-4 11:00' => [1,4] (not range)."""
    Group = apps.get_model("groups", "Group")
    for g in Group.objects.all():
        parsed = parse_days_from_display_name(g.display_name or g.name or "")
        if parsed:
            g.days_of_week = parsed
            g.save(update_fields=["days_of_week"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_add_display_name_is_manual"),
    ]

    operations = [
        migrations.RunPython(backfill_days_from_display_name, noop),
    ]
