# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_add_monthly_fee_lessons_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Aylıq haqq (real AZN)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
