# Generated by Django 6.0.2 on 2026-02-11 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question Topic',
                'verbose_name_plural': 'Question Topics',
                'db_table': 'question_topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='exams/%Y/%m/')),
                ('is_result_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'db_table': 'exam_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('OPEN_SINGLE_VALUE', 'Open Single Value'), ('OPEN_ORDERED', 'Open Ordered'), ('OPEN_UNORDERED', 'Open Unordered'), ('SITUATION', 'Situation')], db_index=True, max_length=30)),
                ('correct_answer', models.JSONField(blank=True, default=dict, null=True)),
                ('answer_rule_type', models.CharField(blank=True, choices=[('EXACT_MATCH', 'Exact Match'), ('ORDERED_MATCH', 'Ordered Match'), ('UNORDERED_MATCH', 'Unordered Match'), ('NUMERIC_EQUAL', 'Numeric Equal')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.questiontopic')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['topic', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='tests.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='tests.question')),
            ],
            options={
                'verbose_name': 'Exam Question',
                'verbose_name_plural': 'Exam Questions',
                'db_table': 'exam_questions',
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tests.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_manual_check', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='tests.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tests.questionoption')),
            ],
            options={
                'verbose_name': 'Exam Answer',
                'verbose_name_plural': 'Exam Answers',
                'db_table': 'exam_answers',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time'], name='exams_start_t_bab18d_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['end_time'], name='exams_end_tim_7705f0_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_status_863d01_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student'], name='exam_attemp_student_bc66a9_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['exam'], name='exam_attemp_exam_id_6e229d_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question'], name='question_op_questio_dc3834_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['attempt'], name='exam_answer_attempt_4bc2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='examanswer',
            index=models.Index(fields=['question'], name='exam_answer_questio_db1085_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic'], name='questions_topic_i_963006_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['type'], name='questions_type_aca5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'),
        ),
    ]
