# Generated by Django 6.0.2 on 2026-02-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_bank_and_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='teacher_pdfs/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(db_column='teacher_id', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher PDF',
                'verbose_name_plural': 'Teacher PDFs',
                'db_table': 'teacher_pdfs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'is_deleted'], name='teacher_pdf_teacher_b03bdd_idx'), models.Index(fields=['created_at'], name='teacher_pdf_created_6a3f56_idx')],
            },
        ),
    ]
