# Generated by Django 6.0.2 on 2026-02-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('tests', '0003_add_teacher_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='max_score',
            field=models.IntegerField(blank=True, help_text='Total points (defaults: Quiz=100, Exam=150)', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='pdf_document',
            field=models.ForeignKey(blank=True, help_text='PDF from library (alternative to pdf_file)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='tests.teacherpdf'),
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tests.exam')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='groups.group')),
            ],
            options={
                'verbose_name': 'Exam Assignment',
                'verbose_name_plural': 'Exam Assignments',
                'db_table': 'exam_assignments',
                'indexes': [models.Index(fields=['exam'], name='exam_assign_exam_id_4b1fff_idx'), models.Index(fields=['group'], name='exam_assign_group_i_7ef457_idx')],
                'unique_together': {('exam', 'group')},
            },
        ),
    ]
