# Generated by Django 6.0.2 on 2026-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_add_exam_assignment_and_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='manual_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teacher-assigned score for manual questions', max_digits=10, null=True),
        ),
    ]
