# Generated by Django 6.0.2 on 2026-02-14 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_examstudentassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examstudentassignment',
            new_name='exam_studen_exam_id_6411b9_idx',
            old_name='exam_studen_exam_id_idx',
        ),
        migrations.RenameIndex(
            model_name='examstudentassignment',
            new_name='exam_studen_student_309fe9_idx',
            old_name='exam_studen_student_idx',
        ),
    ]
