# Generated by Django 6.0.2 on 2026-02-15 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_rename_exam_studen_exam_id_idx_exam_studen_exam_id_6411b9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_rule_type',
            field=models.CharField(blank=True, choices=[('EXACT_MATCH', 'Exact Match'), ('ORDERED_MATCH', 'Ordered Match'), ('UNORDERED_MATCH', 'Unordered Match'), ('NUMERIC_EQUAL', 'Numeric Equal'), ('ORDERED_DIGITS', 'Ordered Digits (sequence matters)'), ('UNORDERED_DIGITS', 'Unordered Digits (set, order irrelevant)')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ExamAttemptCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_canvases/%Y/%m/')),
                ('strokes_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvases', to='tests.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempt_canvases', to='tests.question')),
            ],
            options={
                'verbose_name': 'Exam Attempt Canvas',
                'verbose_name_plural': 'Exam Attempt Canvases',
                'db_table': 'exam_attempt_canvases',
                'indexes': [models.Index(fields=['attempt'], name='exam_attemp_attempt_6a2ee7_idx'), models.Index(fields=['question'], name='exam_attemp_questio_2e01d0_idx')],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
