# Generated by Django 6.0.2 on 2026-02-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_exam_attempt_assignment_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Archived by teacher cleanup'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='questiontopic',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='teacherpdf',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
