# Generated by Django 6.0.2 on 2026-02-16 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0014_add_archived_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam_run"], name="exam_attemp_exam_ru_95da87_idx"
            ),
        ),
    ]
