# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0015_examattempt_exam_attemp_exam_ru_95da87_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="attempt_blueprint",
            field=models.JSONField(
                blank=True,
                help_text="Frozen question/option order and correctOptionId per question for this attempt",
                null=True,
            ),
        ),
    ]
