# Generated by Django 6.0.2 on 2026-02-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_examattempt_attempt_blueprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='is_visible_to_student',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether student can see/restart this attempt (locked after submit)'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='option_order',
            field=models.JSONField(blank=True, help_text='Order of options per question as seen by student (for grading accuracy)', null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, help_text='Order of questions as seen by student (for grading accuracy)', null=True),
        ),
        migrations.CreateModel(
            name='GradingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Total attempt score before change', max_digits=10, null=True)),
                ('new_total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Total attempt score after change', max_digits=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the change', null=True)),
                ('answer', models.ForeignKey(blank=True, help_text='Specific answer that was changed (null if total score changed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_audit_logs', to='tests.examanswer')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_audit_logs', to='tests.examattempt')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grading_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grading Audit Log',
                'verbose_name_plural': 'Grading Audit Logs',
                'db_table': 'grading_audit_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['attempt'], name='grading_aud_attempt_0d47b0_idx'), models.Index(fields=['teacher'], name='grading_aud_teacher_092a19_idx'), models.Index(fields=['changed_at'], name='grading_aud_changed_ba646d_idx')],
            },
        ),
    ]
